[build]
  command = "cd client  && npm install && npm install tailwindcss && npm run build"
  publish = "client/build"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "cd server && npm run dev"
  publish = "client/build"
  functions = "server/functions"